services:
  app:
    volumes: &appvolumes
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./src:/var/www/html:cached

  phpfpm:
    volumes: *appvolumes    

  react:
    build:
      context: ./src/react-frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src/react-frontend:/app:cached
      - /app/node_modules
      - ./src/pub/react:/pub/react
    command: sh -c "npm run build && npm run build -- --watch"
    environment:
      - NODE_ENV=development
    
  phpmyadmin:
    image: linuxserver/phpmyadmin
    env_file: env/db.env
    ports:
      - "8080:80"
    depends_on:
      - db
